--- 
networks: 
  elastic: 
    driver: bridge
services: 
  es01: 
    container_name: es01
    environment: 
      - 
        node.name: es01
      - 
        cluster.name: es-docker-cluster
      - 
        discovery.seed_hosts: 
          - es02
          - es03
      - 
        cluster.initial_master_nodes: "es01,es02,es03"
      - 
        bootstrap.memory_lock: true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 
        xpack.license.self_generated.type: basic
      - 
        xpack.security.enabled: true
    healthcheck: 
      interval: 30s
      retries: 5
      test: "curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi"
      timeout: 10s
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    networks: 
      - elastic
    ports: 
      - "9200:9200"
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
    volumes: 
      - "data01:/usr/share/elasticsearch/data"
  es02: 
    container_name: es02
    environment: 
      - 
        node.name: es02
      - 
        cluster.name: es-docker-cluster
      - 
        discovery.seed_hosts: 
          - es01
          - es03
      - 
        cluster.initial_master_nodes: "es01,es02,es03"
      - 
        bootstrap.memory_lock: true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 
        xpack.license.self_generated.type: basic
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    networks: 
      - elastic
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
    volumes: 
      - "data02:/usr/share/elasticsearch/data"
  es03: 
    container_name: es03
    environment: 
      - 
        node.name: es03
      - 
        cluster.name: es-docker-cluster
      - 
        discovery.seed_hosts: 
          - es01
          - es02
      - 
        cluster.initial_master_nodes: 
          - es01
          - es02
          - es03
      - 
        bootstrap.memory_lock: true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 
        xpack.license.self_generated.type: basic
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    networks: 
      - elastic
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
    volumes: 
      - "data03:/usr/share/elasticsearch/data"
  kib01: 
    container_name: kib01
    depends_on: 
      - 
        es01: 
          condition: service_healthy
    environment: 
      ELASTICSEARCH_HOSTS: "https://es01:9200"
      ELASTICSEARCH_URL: "https://es01:9200"
      SERVERNAME: localhost
    image: "docker.elastic.co/kibana/kibana:${ELK_VERSION}"
    networks: 
      - elastic
    ports: 
      - "5601:5601"
version: "3.5"
volumes: 
  data01: 
    driver: local
  data02: 
    driver: local
  data03: 
    driver: local
